services:
  web:
    build: .
    ports:
      - "8512:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager
    ports:
      - "5532:5432"
      
  redis:
    image: redis:7
    ports:
      - "6532:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: